dict_paldeck = {
    1: {'Name': 'Lamball', 'Power': 1470, 'Order': 27, 'ImageUrl': 'https://palworld.wiki.gg/images/e/ee/Lamball_icon.png'},
    2: {'Name': 'Cattiva', 'Power': 1460, 'Order': 46, 'ImageUrl': 'https://palworld.wiki.gg/images/6/6d/Cattiva_icon.png'},
    3: {'Name': 'Chikipi', 'Power': 1500, 'Order': 62, 'ImageUrl': 'https://palworld.wiki.gg/images/5/54/Chikipi_icon.png'},
    4: {'Name': 'Lifmunk', 'Power': 1430, 'Order': 7, 'ImageUrl': 'https://palworld.wiki.gg/images/8/89/Lifmunk_icon.png'},
    5: {'Name': 'Foxparks', 'Power': 1400, 'Order': 20, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/b/bf/T_Kitsunebi_icon_normal.png?width=325'},
    6: {'Name': 'Fuack', 'Power': 1330, 'Order': 59, 'ImageUrl': 'https://palworld.wiki.gg/images/a/ab/Fuack_icon.png'},
    7: {'Name': 'Sparkit', 'Power': 1410, 'Order': 65, 'ImageUrl': 'https://palworld.wiki.gg/images/5/56/Sparkit_icon.png'},
    8: {'Name': 'Tanzee', 'Power': 1250, 'Order': 107, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/f/f7/T_Monkey_icon_normal.png'},
    9: {'Name': 'Rooby', 'Power': 1155, 'Order': 138, 'ImageUrl': 'https://palworld.wiki.gg/images/b/b2/Rooby_icon.png'},
    10: {'Name': 'Pengullet', 'Power': 1350, 'Order': 23, 'ImageUrl': 'https://palworld.wiki.gg/images/5/5f/Pengullet_icon.png'},
    11: {'Name': 'Penking', 'Power': 520, 'Order': 122, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/6/69/T_CaptainPenguin_icon_normal.png'},
    12.1: {'Name': 'Jolthog', 'Power': 1370, 'Order': 17, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/2/23/T_Hedgehog_icon_normal.png'},
    12.2: {'Name': 'Jolthog Cryst', 'Power': 1360, 'Order': 18, 'ImageUrl': 'https://palworld.wiki.gg/images/b/b7/Jolthog_Cryst_icon.png'},
    13.1: {'Name': 'Gumoss', 'Power': 1240, 'Order': 112, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/6/61/T_PlantSlime_icon_normal.png?width=325'},
    13.2: {'Name': 'Gumoss (Special)', 'Power': 1240, 'Order': 113, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/6/61/T_PlantSlime_icon_normal.png?width=325'},
    14: {'Name': 'Vixy', 'Power': 1450, 'Order': 79, 'ImageUrl': 'https://palworld.wiki.gg/images/f/f6/Vixy_icon.png'},
    15: {'Name': 'Hoocrates', 'Power': 1390, 'Order': 82, 'ImageUrl': 'https://palworld.wiki.gg/images/d/de/Hoocrates_icon.png'},
    16: {'Name': 'Teafant', 'Power': 1490, 'Order': 14, 'ImageUrl': 'https://palworld.wiki.gg/images/0/09/Teafant_icon.png'},
    17: {'Name': 'Depresso', 'Power': 1380, 'Order': 47, 'ImageUrl': 'https://palworld.wiki.gg/images/5/52/Depresso_icon.png'},
    18: {'Name': 'Cremis', 'Power': 1455, 'Order': 135, 'ImageUrl': 'https://palworld.wiki.gg/images/c/c9/Cremis_icon.png'},
    19: {'Name': 'Daedream', 'Power': 1230, 'Order': 106, 'ImageUrl': 'https://palworld.wiki.gg/images/4/43/Daedream_icon.png'},
    20: {'Name': 'Rushoar', 'Power': 1130, 'Order': 6, 'ImageUrl': 'https://palworld.wiki.gg/images/1/18/Rushoar_icon.png'},
    21: {'Name': 'Nox', 'Power': 1180, 'Order': 121, 'ImageUrl': 'https://palworld.wiki.gg/images/d/d4/Nox_icon.png'},
    22: {'Name': 'Fuddler', 'Power': 1220, 'Order': 101, 'ImageUrl': 'https://palworld.wiki.gg/images/a/a5/Fuddler_icon.png'},
    23: {'Name': 'Killamari', 'Power': 1290, 'Order': 85, 'ImageUrl': 'https://palworld.wiki.gg/images/4/40/Killamari_icon.png'},
    24.1: {'Name': 'Mau', 'Power': 1480, 'Order': 4, 'ImageUrl': 'https://palworld.wiki.gg/images/9/96/Mau_icon.png'},
    24.2: {'Name': 'Mau Cryst', 'Power': 1440, 'Order': 5, 'ImageUrl': 'https://palworld.wiki.gg/images/c/c0/Mau_Cryst_icon.png'},
    25: {'Name': 'Celaray', 'Power': 870, 'Order': 128, 'ImageUrl': 'https://palworld.wiki.gg/images/0/0f/Celaray_icon.png'},
    26: {'Name': 'Direhowl', 'Power': 1060, 'Order': 15, 'ImageUrl': 'https://palworld.wiki.gg/images/a/a6/Direhowl_icon.png'},
    27: {'Name': 'Tocotoco', 'Power': 1340, 'Order': 8, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/0/0c/T_ColorfulBird_icon_normal.png'},
    28: {'Name': 'Flopie', 'Power': 1280, 'Order': 91, 'ImageUrl': 'https://palworld.wiki.gg/images/5/51/Flopie_icon.png'},
    29: {'Name': 'Mozzarina', 'Power': 910, 'Order': 86, 'ImageUrl': 'https://palworld.wiki.gg/images/5/51/Mozzarina_icon.png'},
    30: {'Name': 'Bristla', 'Power': 1320, 'Order': 21, 'ImageUrl': 'https://palworld.wiki.gg/images/b/b6/Bristla_icon.png'},
    31.1: {'Name': 'Gobfin', 'Power': 1090, 'Order': 25, 'ImageUrl': 'https://palworld.wiki.gg/images/f/fd/Gobfin_icon.png'},
    31.2: {'Name': 'Gobfin Ignis', 'Power': 1100, 'Order': 26, 'ImageUrl': 'https://palworld.wiki.gg/images/thumb/d/d3/Gobfin_Ignis_icon.png/300px-Gobfin_Ignis_icon.png'},
    32.1: {'Name': 'Hangyu', 'Power': 1420, 'Order': 31, 'ImageUrl': 'https://palworld.wiki.gg/images/9/9c/Hangyu_icon.png'},
    32.2: {'Name': 'Hangyu Cryst', 'Power': 1422, 'Order': 32, 'ImageUrl': 'https://palworld.wiki.gg/images/c/c0/Hangyu_Cryst_icon.png'},
    33.1: {'Name': 'Mossanda', 'Power': 430, 'Order': 97, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/a/ab/T_GrassPanda_icon_normal.png'},
    33.2: {'Name': 'Mossanda Lux', 'Power': 390, 'Order': 98, 'ImageUrl': 'https://palworld.wiki.gg/images/6/62/Mossanda_Lux_icon.png'},
    34: {'Name': 'Woolipop', 'Power': 1190, 'Order': 39, 'ImageUrl': 'https://palworld.wiki.gg/images/a/a7/Woolipop_icon.png'},
    35: {'Name': 'Caprity', 'Power': 930, 'Order': 75, 'ImageUrl': 'https://palworld.wiki.gg/images/8/86/Caprity_icon.png'},
    36: {'Name': 'Melpaca', 'Power': 890, 'Order': 41, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/9/99/T_Alpaca_icon_normal.png'},
    37.1: {'Name': 'Eikthyrdeer', 'Power': 920, 'Order': 9, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/1/1b/T_Deer_icon_normal.png'},
    37.2: {'Name': 'Eikthyrdeer Terra', 'Power': 900, 'Order': 10, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/9/9f/T_Deer_Ground_icon_normal.png?width=325'},
    38.1: {'Name': 'Nitewing', 'Power': 420, 'Order': 90, 'ImageUrl': 'https://palworld.wiki.gg/images/f/f8/Nitewing_icon.png'},
    39: {'Name': 'Ribunny', 'Power': 1310, 'Order': 117, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/e/e9/T_PinkRabbit_icon_normal.png'},
    40.1: {'Name': 'Incineram', 'Power': 590, 'Order': 2, 'ImageUrl': 'https://palworld.wiki.gg/images/0/0b/Incineram_icon.png'},
    40.2: {'Name': 'Incineram Noct', 'Power': 580, 'Order': 3, 'ImageUrl': 'https://palworld.wiki.gg/images/thumb/d/d7/Incineram_Noct_icon.png/300px-Incineram_Noct_icon.png'},
    41: {'Name': 'Cinnamoth', 'Power': 490, 'Order': 132, 'ImageUrl': 'https://palworld.wiki.gg/images/a/a5/Cinnamoth_icon.png'},
    42: {'Name': 'Arsox', 'Power': 790, 'Order': 99, 'ImageUrl': 'https://palworld.wiki.gg/images/2/21/Arsox_icon.png'},
    43: {'Name': 'Dumud', 'Power': 895, 'Order': 136, 'ImageUrl': 'https://palworld.wiki.gg/images/8/80/Dumud_icon.png'},
    44: {'Name': 'Cawgnito', 'Power': 1080, 'Order': 44, 'ImageUrl': 'https://palworld.wiki.gg/images/d/d2/Cawgnito_icon.png'},
    45.1: {'Name': 'Leezpunk', 'Power': 1120, 'Order': 57, 'ImageUrl': 'https://palworld.wiki.gg/images/3/33/Leezpunk_icon.png'},
    45.2: {'Name': 'Leezpunk Ignis', 'Power': 1140, 'Order': 58, 'ImageUrl': 'https://palworld.wiki.gg/images/7/7e/Leezpunk_Ignis_icon.png'},
    46: {'Name': 'Loupmoon', 'Power': 950, 'Order': 30, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/1/1e/T_Werewolf_icon_normal.png'},
    47: {'Name': 'Galeclaw', 'Power': 1030, 'Order': 12, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/0/0b/T_Eagle_icon_normal.png?width=325'},
    48.1: {'Name': 'Robinquill', 'Power': 1020, 'Order': 52, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/8/8d/T_RobinHood_icon_normal.png?width=325'},
    48.2: {'Name': 'Robinquill Terra', 'Power': 1000, 'Order': 53, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/4/45/T_RobinHood_Ground_icon_normal.png?width=325'},
    49: {'Name': 'Gorirat', 'Power': 1040, 'Order': 16, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/f/fa/T_Gorilla_icon_normal.png?width=325'},
    50: {'Name': 'Beegarde', 'Power': 1070, 'Order': 95, 'ImageUrl': 'https://palworld.wiki.gg/images/3/37/Beegarde_icon.png'},
    51: {'Name': 'Elizabee', 'Power': 330, 'Order': 94, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/d/db/T_QueenBee_icon_normal.png'},
    52: {'Name': 'Grintale', 'Power': 510, 'Order': 131, 'ImageUrl': 'https://palworld.wiki.gg/images/4/4d/Grintale_icon.png'},
    53: {'Name': 'Swee', 'Power': 1300, 'Order': 114, 'ImageUrl': 'https://palworld.wiki.gg/images/d/d5/Swee_icon.png'},
    54: {'Name': 'Sweepa', 'Power': 410, 'Order': 115, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/6/65/T_MopKing_icon_normal.png?width=325'},
    55: {'Name': 'Chillet', 'Power': 800, 'Order': 123, 'ImageUrl': 'https://palworld.wiki.gg/images/0/0f/Chillet_icon.png'},
    56: {'Name': 'Univolt', 'Power': 680, 'Order': 19, 'ImageUrl': 'https://palworld.wiki.gg/images/b/ba/Univolt_icon.png'},
    57: {'Name': 'Foxcicle', 'Power': 760, 'Order': 104, 'ImageUrl': 'https://palworld.wiki.gg/images/2/2d/Foxcicle_icon.png'},
    58.1: {'Name': 'Pyrin', 'Power': 360, 'Order': 35, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/7/7c/T_FireKirin_icon_normal.png'},
    58.2: {'Name': 'Pyrin Noct', 'Power': 240, 'Order': 36, 'ImageUrl': 'https://palworld.wiki.gg/images/8/81/Pyrin_Noct_icon.png'},
    59: {'Name': 'Reindrix', 'Power': 880, 'Order': 76, 'ImageUrl': 'https://palworld.wiki.gg/images/1/1e/Reindrix_icon.png'},
    60: {'Name': 'Rayhound', 'Power': 740, 'Order': 100, 'ImageUrl': 'https://palworld.wiki.gg/images/d/dc/Rayhound_icon.png'},
    61: {'Name': 'Kitsun', 'Power': 830, 'Order': 56, 'ImageUrl': 'https://palworld.wiki.gg/images/0/00/Kitsun_icon.png'},
    62: {'Name': 'Dazzi', 'Power': 1210, 'Order': 24, 'ImageUrl': 'https://palworld.wiki.gg/images/6/62/Dazzi_icon.png'},
    63: {'Name': 'Lunaris', 'Power': 1110, 'Order': 22, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/d/d2/T_Mutant_icon_normal.png?width=325'},
    64.1: {'Name': 'Dinossom', 'Power': 820, 'Order': 63, 'ImageUrl': 'https://palworld.wiki.gg/images/9/9e/Dinossom_icon.png'},
    64.2: {'Name': 'Dinossom Lux', 'Power': 810, 'Order': 64, 'ImageUrl': 'https://palworld.wiki.gg/images/8/8f/Dinossom_Lux_icon.png'},
    65.1: {'Name': 'Surfent', 'Power': 560, 'Order': 42, 'ImageUrl': 'https://static0.hardcoregamerimages.com/wordpress/wp-content/uploads/2024/01/palworld-surfent-icon-2.png'},
    65.2: {'Name': 'Surfent Terra', 'Power': 550, 'Order': 43, 'ImageUrl': 'https://genshinlab.com/wp-content/uploads/2024/01/Surfent-Terra.webp'},
    66: {'Name': 'Maraith', 'Power': 1150, 'Order': 51, 'ImageUrl': 'https://palworld.wiki.gg/images/d/da/Maraith_icon.png'},
    67: {'Name': 'Digtoise', 'Power': 850, 'Order': 11, 'ImageUrl': 'https://palworld.wiki.gg/images/3/3b/Digtoise_icon.png'},
    68: {'Name': 'Tombat', 'Power': 750, 'Order': 96, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/d/d8/T_CatBat_icon_normal.png'},
    69: {'Name': 'Lovander', 'Power': 940, 'Order': 81, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/3/37/T_PinkLizard_icon_normal.png'},
    70: {'Name': 'Flambelle', 'Power': 1405, 'Order': 137, 'ImageUrl': 'https://palworld.wiki.gg/images/c/ca/Flambelle_icon.png'},
    71.1: {'Name': 'Vanwyrm', 'Power': 660, 'Order': 60, 'ImageUrl': 'https://palworld.wiki.gg/images/3/34/Vanwyrm_icon.png'},
    71.2: {'Name': 'Vanwyrm Cryst', 'Power': 620, 'Order': 61, 'ImageUrl': 'https://palworld.wiki.gg/images/b/b7/Vanwyrm_Cryst_icon.png'},
    72: {'Name': 'Bushi', 'Power': 640, 'Order': 127, 'ImageUrl': 'https://palworld.wiki.gg/images/1/1d/Bushi_icon.png'},
    73: {'Name': 'Beakon', 'Power': 220, 'Order': 118, 'ImageUrl': 'https://palworld.wiki.gg/images/b/b7/Beakon_icon.png'},
    74: {'Name': 'Ragnahawk', 'Power': 380, 'Order': 126, 'ImageUrl': 'https://palworld.wiki.gg/images/6/6f/Ragnahawk_icon.png'},
    75: {'Name': 'Katress', 'Power': 700, 'Order': 116, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/b/bd/T_CatMage_icon_normal.png'},
    76: {'Name': 'Wixen', 'Power': 1160, 'Order': 80, 'ImageUrl': 'https://palworld.wiki.gg/images/a/a9/Wixen_icon.png'},
    77: {'Name': 'Verdash', 'Power': 990, 'Order': 103, 'ImageUrl': 'https://palworld.wiki.gg/images/a/a2/Verdash_icon.png'},
    78: {'Name': 'Vaelet', 'Power': 1050, 'Order': 89, 'ImageUrl': 'https://palworld.wiki.gg/images/1/1d/Vaelet_icon.png'},
    79: {'Name': 'Sibelyx', 'Power': 450, 'Order': 78, 'ImageUrl': 'https://palworld.wiki.gg/images/4/49/Sibelyx_icon.png'},
    80.1: {'Name': 'Elphidran', 'Power': 540, 'Order': 37, 'ImageUrl': 'https://palworld.wiki.gg/images/8/8d/Elphidran_icon.png'},
    80.2: {'Name': 'Elphidran Aqua', 'Power': 530, 'Order': 38, 'ImageUrl': 'https://palworld.wiki.gg/images/f/fd/Elphidran_Aqua_icon.png'},
    81.1: {'Name': 'Kelpsea', 'Power': 1260, 'Order': 83, 'ImageUrl': 'https://palworld.wiki.gg/images/5/5f/Kelpsea_icon.png'},
    81.2: {'Name': 'Kelpsea Ignis', 'Power': 1270, 'Order': 84, 'ImageUrl': 'https://palworld.wiki.gg/images/0/05/Kelpsea_Ignis_icon.png'},
    82: {'Name': 'Azurobe', 'Power': 500, 'Order': 45, 'ImageUrl': 'https://palworld.wiki.gg/images/b/bc/Azurobe_icon.png'},
    83: {'Name': 'Cryolinx', 'Power': 130, 'Order': 40, 'ImageUrl': 'https://palworld.wiki.gg/images/3/38/Cryolinx_icon.png'},
    84.1: {'Name': 'Blazehowl', 'Power': 710, 'Order': 108, 'ImageUrl': 'https://palworld.wiki.gg/images/9/97/Blazehowl_icon.png'},
    84.2: {'Name': 'Blazehowl Noct', 'Power': 670, 'Order': 109, 'ImageUrl': 'https://palworld.wiki.gg/images/d/d1/Blazehowl_Noct_icon.png'},
    85.1: {'Name': 'Relaxaurus', 'Power': 280, 'Order': 54, 'ImageUrl': 'https://palworld.wiki.gg/images/6/6f/Relaxaurus_icon.png'},
    85.2: {'Name': 'Relaxaurus Lux', 'Power': 270, 'Order': 55, 'ImageUrl': 'https://palworld.wiki.gg/images/7/7e/Relaxaurus_Lux_icon.png'},
    86.1: {'Name': 'Broncherry', 'Power': 860, 'Order': 71, 'ImageUrl': 'https://palworld.wiki.gg/images/5/5f/Broncherry_icon.png'},
    86.2: {'Name': 'Broncherry Aqua', 'Power': 840, 'Order': 72, 'ImageUrl': 'https://palworld.wiki.gg/images/3/38/Broncherry_Aqua_icon.png'},
    87: {'Name': 'Petallia', 'Power': 780, 'Order': 130, 'ImageUrl': 'https://palworld.wiki.gg/images/6/65/Petallia_icon.png'},
    88.1: {'Name': 'Reptyro', 'Power': 320, 'Order': 49, 'ImageUrl': 'https://palworld.wiki.gg/images/f/f5/Reptyro_icon.png'},
    88.2: {'Name': 'Ice Reptyro', 'Power': 230, 'Order': 50, 'ImageUrl': 'https://palworld.wiki.gg/images/c/c1/Reptyro_Cryst_icon.png'},
    89.1: {'Name': 'Kingpaca', 'Power': 470, 'Order': 110, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/b/b5/T_KingAlpaca_icon_normal.png'},
    89.2: {'Name': 'Ice Kingpaca', 'Power': 440, 'Order': 111, 'ImageUrl': 'https://palworld.wiki.gg/images/a/a2/Kingpaca_Cryst_icon.png'},
    90.1: {'Name': 'Mammorest', 'Power': 300, 'Order': 68, 'ImageUrl': 'https://palworld.wiki.gg/images/2/27/Mammorest_icon.png'},
    90.2: {'Name': 'Mammorest Cryst', 'Power': 290, 'Order': 69, 'ImageUrl': 'https://palworld.wiki.gg/images/e/e4/Mammorest_Cryst_icon.png'},
    91: {'Name': 'Wumpo', 'Power': 460, 'Order': 87, 'ImageUrl': 'https://palworld.wiki.gg/images/a/a7/Wumpo_icon.png'},
    91.1: {'Name': 'Wumpo Botan', 'Power': 480, 'Order': 88, 'ImageUrl': 'https://palworld.wiki.gg/images/d/da/Wumpo_Botan_icon.png'},
    92: {'Name': 'Warsect', 'Power': 340, 'Order': 119, 'ImageUrl': 'https://paldex.io/cdn-cgi/image/format=auto,width=300/images/pal-icons/T_HerculesBeetle_icon_normal.png'},
    93: {'Name': 'Fenglope', 'Power': 980, 'Order': 48, 'ImageUrl': 'https://palworld.wiki.gg/images/a/a5/Fenglope_icon.png'},
    94: {'Name': 'Felbat', 'Power': 1010, 'Order': 70, 'ImageUrl': 'https://static0.hardcoregamerimages.com/wordpress/wp-content/uploads/2024/01/palworld-felbat-icon-2.png'},
    95: {'Name': 'Quivern', 'Power': 350, 'Order': 124, 'ImageUrl': 'https://palworld.wiki.gg/images/d/d5/Quivern_icon.png'},
    96: {'Name': 'Blazamut', 'Power': 10, 'Order': 74, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/e/eb/T_KingBahamut_icon_normal.png'},
    97: {'Name': 'Helzephyr', 'Power': 190, 'Order': 125, 'ImageUrl': 'https://palworld.wiki.gg/images/9/98/Helzephyr_icon.png'},
    98: {'Name': 'Astegon', 'Power': 150, 'Order': 102, 'ImageUrl': 'https://palworld.wiki.gg/images/d/d0/Astegon_icon.png'},
    99: {'Name': 'Menasting', 'Power': 260, 'Order': 133, 'ImageUrl': 'https://palworld.wiki.gg/images/2/23/Menasting_icon.png'},
    100: {'Name': 'Anubis', 'Power': 570, 'Order': 1, 'ImageUrl': 'https://paldex.io/cdn-cgi/image/format=auto,width=300/images/pal-icons/T_Anubis_icon_normal.png'},
    101.1: {'Name': 'Jormuntide', 'Power': 310, 'Order': 28, 'ImageUrl': 'https://palworld.wiki.gg/images/e/e7/Jormuntide_icon.png'},
    101.2: {'Name': 'Jormuntide Ignis', 'Power': 315, 'Order': 29, 'ImageUrl': 'https://static0.hardcoregamerimages.com/wordpress/wp-content/uploads/2024/01/palworld-jormuntide-ignis-icon-2.png'},
    102.1: {'Name': 'Suzaku', 'Power': 50, 'Order': 33, 'ImageUrl': 'https://paldex.io/cdn-cgi/image/format=auto,width=300/images/pal-icons/T_Suzaku_icon_normal.png'},
    102.2: {'Name': 'Suzaku Aqua', 'Power': 30, 'Order': 34, 'ImageUrl': 'https://paldex.io/cdn-cgi/image/format=auto,width=300/images/pal-icons/T_Suzaku_Water_icon_normal.png'},
    103: {'Name': 'Grizzbolt', 'Power': 200, 'Order': 13, 'ImageUrl': 'https://palworld.wiki.gg/images/3/3c/Grizzbolt_icon.png'},
    104.1: {'Name': 'Lyleen', 'Power': 250, 'Order': 92, 'ImageUrl': 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/palworld/d/d0/T_LilyQueen_icon_normal.png?width=325'},
    104.2: {'Name': 'Lyleen Noct', 'Power': 210, 'Order': 93, 'ImageUrl': 'https://palworld.wiki.gg/images/6/6b/Lyleen_Noct_icon.png'},
    105: {'Name': 'Faleris', 'Power': 370, 'Order': 73, 'ImageUrl': 'https://palworld.wiki.gg/images/b/b9/Faleris_icon.png'},
    106: {'Name': 'Orserk', 'Power': 140, 'Order': 134, 'ImageUrl': 'https://palworld.wiki.gg/images/3/3e/Orserk_icon.png'},
    107: {'Name': 'Shadowbeak', 'Power': 60, 'Order': 77, 'ImageUrl': 'https://palworld.wiki.gg/images/0/00/Shadowbeak_icon.png'},
    108: {'Name': 'Paladius', 'Power': 80, 'Order': 120, 'ImageUrl': 'https://palworld.wiki.gg/images/6/63/Paladius_icon.png'},
    109: {'Name': 'Necromus', 'Power': 70, 'Order': 129, 'ImageUrl': 'https://palworld.wiki.gg/images/1/17/Necromus_icon.png'},
    110.1: {'Name': 'Frostallion', 'Power': 120, 'Order': 66, 'ImageUrl': 'https://palworld.wiki.gg/images/b/b1/Frostallion_icon.png'},
    110.2: {'Name': 'Frostallion Noct', 'Power': 100, 'Order': 67, 'ImageUrl': 'https://palworld.wiki.gg/images/a/a0/Frostallion_Noct_icon.png'},
    111: {'Name': 'Jetragon', 'Power': 90, 'Order': 105, 'ImageUrl': 'https://palworld.wiki.gg/images/a/ab/Jetragon_icon.png'}
}

unique_combos = {
    "Relaxaurus-Lux": "Relaxaurus+Sparkit",
    "Incineram-Noct": "Incineram+Maraith",
    "Mau-Cryst": "Mau+Pengullet",
    "Vanwyrm-Cryst": "Vanwyrm+Foxcicle",
    "Eikthyrdeer-Terra": "Eikthyrdeer+Hangyu",
    "Elphidran-Aqua": "Elphidran+Surfent",
    "Pyrin-Noct": "Pyrin+Katress",
    "Mammorest-Cryst": "Mammorest+Wumpo",
    "Mossanda-Lux": "Mossanda+Grizzbolt",
    "Dinossom-Lux": "Dinossom+Rayhound",
    "Jolthog-Cryst": "Jolthog+Pengullet",
    "Frostallion-Noct": "Frostallion+Helzephyr",
    "Ice-Kingpaca": "Kingpaca+Reindrix",
    "Lyleen-Noct": "Lyleen+Menasting",
    "Leezpunk-Ignis": "Leezpunk+Flambelle",
    "Blazehowl-Noct": "Blazehowl+Felbat",
    "Robinquill-Terra": "Robinquill+Fuddler",
    "Broncherry-Aqua": "Broncherry+Fuack",
    "Surfent-Terra": "Surfent+Dumud",
    "Gobfin-Ignis": "Gobfin+Rooby",
    "Suzaku-Aqua": "Suzaku+Jormuntide",
    "Ice-Reptyro": "Reptyro+Foxcicle",
    "Hangyu-Cryst": "Hangyu+Swee",
    "Lyleen": "Mossanda+Petallia",
    "Faleris": "Vanwyrm+Anubis",
    "Grizzbolt": "Mossanda+Rayhound",
    "Orserk": "Grizzbolt+Relaxaurus",
    "Shadowbeak": "Kitsun+Astegon",
    "Frostallion": "Frostallion+Frostallion",
    "Jetragon": "Jetragon+Jetragon",
    "Paladius": "Paladius+Paladius",
    "Necromus": "Necromus+Necromus",
    "Jormuntide-Ignis": "Jormuntide-Ignis+Jormuntide-Ignis"
}
